package github.paz.awardportal.pdf;

import lombok.Getter;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.List;

/*
Expected output files generated by pdflatex against a given template file.
 */
@Getter
public class PdfLatexFiles {
    private Path texTemplate;
    private Path pdfFile;
    private Path auxFile;
    private Path logFile;
    private Path temp64File;

    public PdfLatexFiles(Path texTemplate) {
        String texTemplateFileName = getFileName(texTemplate);
        String pdfFileName = changeExtension(texTemplateFileName, "pdf");
        String auxFileName = changeExtension(texTemplateFileName, "aux");
        String logFileName = changeExtension(texTemplateFileName, "log");
        String temp64FileName = changeExtension(texTemplateFileName, "64");

        this.texTemplate = texTemplate;
        pdfFile = Paths.get(pdfFileName);
        auxFile = Paths.get(auxFileName);
        logFile = Paths.get(logFileName);
        temp64File = Paths.get(temp64FileName);

    }

    public List<Path> getAll() {
        return Arrays.asList(texTemplate, pdfFile, auxFile, logFile, temp64File);
    }

    private String getFileName(Path path) {
        return path.getFileName().toString();
    }

    private String changeExtension(String fileName, String newExtension) {
        int pos = fileName.lastIndexOf('.');
        String noExtension = fileName.substring(0, pos);
        return noExtension + '.' + newExtension;

    }
}
