export const FETCH_AWARDS_BEGIN = "FETCH_AWARDS_BEGIN";
export const FETCH_AWARDS_SUCCESS = "FETCH_AWARDS_SUCCESS";
export const FETCH_AWARDS_FAILURE = "FETCH_AWARDS_FAILURE";

export const FETCH_AWARD_BEGIN = "FETCH_AWARD_BEGIN";
export const FETCH_AWARD_SUCCESS = "FETCH_AWARD_SUCCESS";
export const FETCH_AWARD_FAILURE = "FETCH_AWARD_FAILURE";

export const FETCH_AWARD_BY_GRANTER_BEGIN = "FETCH_BY_GRANTER_AWARD_BEGIN";
export const FETCH_AWARD_BY_GRANTER_SUCCESS = "FETCH_BY_GRANTER_AWARD_SUCCESS";
export const FETCH_AWARD_BY_GRANTER_FAILURE = "FETCH_BY_GRANTER_AWARD_FAILURE";

export const FETCH_AWARD_BY_RECIPIENT_BEGIN = "FETCH_BY_RECIPIENT_AWARD_BEGIN";
export const FETCH_AWARD_BY_RECIPIENT_SUCCESS = "FETCH_BY_RECIPIENT_AWARD_SUCCESS";
export const FETCH_AWARD_BY_RECIPIENT_FAILURE = "FETCH_BY_RECIPIENT_AWARD_FAILURE";

export const CREATE_AWARD_BEGIN = "CREATE_AWARD_BEGIN";
export const CREATE_AWARD_SUCCESS = "CREATE_AWARD_SUCCESS";
export const CREATE_AWARD_FAILURE = "CREATE_AWARD_FAILURE";

export const DELETE_AWARD_BEGIN = "DELETE_AWARD_BEGIN";
export const DELETE_AWARD_SUCCESS = "DELETE_AWARD_SUCCESS";
export const DELETE_AWARD_FAILURE = "DELETE_AWARD_FAILURE";

export const UPDATE_AWARD_PASSWORD_BEGIN = "UPDATE_AWARD_PASSWORD_BEGIN";
export const UPDATE_AWARD_PASSWORD_SUCCESS = "UPDATE_AWARD_PASSWORD_SUCCESS";
export const UPDATE_AWARD_PASSWORD_FAILURE = "UPDATE_AWARD_PASSWORD_FAILURE";

export default {
  FETCH_AWARDS_BEGIN,
  FETCH_AWARDS_SUCCESS,
  FETCH_AWARDS_FAILURE,

  FETCH_AWARD_BEGIN,
  FETCH_AWARD_SUCCESS,
  FETCH_AWARD_FAILURE,

  CREATE_AWARD_BEGIN,
  CREATE_AWARD_SUCCESS,
  CREATE_AWARD_FAILURE,

  FETCH_AWARD_BY_GRANTER_BEGIN,
  FETCH_AWARD_BY_GRANTER_SUCCESS,
  FETCH_AWARD_BY_GRANTER_FAILURE,

  FETCH_AWARD_BY_RECIPIENT_BEGIN,
  FETCH_AWARD_BY_RECIPIENT_SUCCESS,
  FETCH_AWARD_BY_RECIPIENT_FAILURE,

  DELETE_AWARD_BEGIN,
  DELETE_AWARD_SUCCESS,
  DELETE_AWARD_FAILURE,

  UPDATE_AWARD_PASSWORD_BEGIN,
  UPDATE_AWARD_PASSWORD_SUCCESS,
  UPDATE_AWARD_PASSWORD_FAILURE
}
