export const FETCH_AWARD_TYPES_BEGIN = "FETCH_AWARD_TYPES_BEGIN";
export const FETCH_AWARD_TYPES_SUCCESS = "FETCH_AWARD_TYPES_SUCCESS";
export const FETCH_AWARD_TYPES_FAILURE = "FETCH_AWARD_TYPES_FAILURE";

export const FETCH_AWARD_TYPE_BEGIN = "FETCH_AWARD_TYPE_BEGIN";
export const FETCH_AWARD_TYPE_SUCCESS = "FETCH_AWARD_TYPE_SUCCESS";
export const FETCH_AWARD_TYPE_FAILURE = "FETCH_AWARD_TYPE_FAILURE";

export const CREATE_AWARD_TYPE_BEGIN = "CREATE_AWARD_TYPE_BEGIN";
export const CREATE_AWARD_TYPE_SUCCESS = "CREATE_AWARD_TYPE_SUCCESS";
export const CREATE_AWARD_TYPE_FAILURE = "CREATE_AWARD_TYPE_FAILURE";

export const DELETE_AWARD_TYPE_BEGIN = "DELETE_AWARD_TYPE_BEGIN";
export const DELETE_AWARD_TYPE_SUCCESS = "DELETE_AWARD_TYPE_SUCCESS";
export const DELETE_AWARD_TYPE_FAILURE = "DELETE_AWARD_TYPE_FAILURE";

export default {
  FETCH_AWARD_TYPES_BEGIN,
  FETCH_AWARD_TYPES_SUCCESS,
  FETCH_AWARD_TYPES_FAILURE,

  FETCH_AWARD_TYPE_BEGIN,
  FETCH_AWARD_TYPE_SUCCESS,
  FETCH_AWARD_TYPE_FAILURE,

  CREATE_AWARD_TYPE_BEGIN,
  CREATE_AWARD_TYPE_SUCCESS,
  CREATE_AWARD_TYPE_FAILURE,

  DELETE_AWARD_TYPE_BEGIN,
  DELETE_AWARD_TYPE_SUCCESS,
  DELETE_AWARD_TYPE_FAILURE,
}
