export const FETCH_OFFICES_BEGIN = 'FETCH_OFFICES_BEGIN';
export const FETCH_OFFICES_SUCCESS = 'FETCH_OFFICES_SUCCESS';
export const FETCH_OFFICES_FAILURE = 'FETCH_OFFICES_FAILURE';

export const FETCH_OFFICE_BEGIN = 'FETCH_OFFICE_BEGIN';
export const FETCH_OFFICE_SUCCESS = 'FETCH_OFFICE_SUCCESS';
export const FETCH_OFFICE_FAILURE = 'FETCH_OFFICE_FAILURE';

export const CREATE_OFFICE_BEGIN = 'CREATE_OFFICE_BEGIN';
export const CREATE_OFFICE_SUCCESS = 'CREATE_OFFICE_SUCCESS';
export const CREATE_OFFICE_FAILURE = 'CREATE_OFFICE_FAILURE';

export const UPDATE_OFFICE_BEGIN = 'UPDATE_OFFICE_BEGIN';
export const UPDATE_OFFICE_SUCCESS = 'UPDATE_OFFICE_SUCCESS';
export const UPDATE_OFFICE_FAILURE = 'UPDATE_OFFICE_FAILURE';

export const DELETE_OFFICE_BEGIN = 'DELETE_OFFICE_BEGIN';
export const DELETE_OFFICE_SUCCESS = 'DELETE_OFFICE_SUCCESS';
export const DELETE_OFFICE_FAILURE = 'DELETE_OFFICE_FAILURE';

export default {
  FETCH_OFFICES_BEGIN,
  FETCH_OFFICES_SUCCESS,
  FETCH_OFFICES_FAILURE,

  FETCH_OFFICE_BEGIN,
  FETCH_OFFICE_SUCCESS,
  FETCH_OFFICE_FAILURE,

  CREATE_OFFICE_BEGIN,
  CREATE_OFFICE_SUCCESS,
  CREATE_OFFICE_FAILURE,

  UPDATE_OFFICE_BEGIN,
  UPDATE_OFFICE_SUCCESS,
  UPDATE_OFFICE_FAILURE,

  DELETE_OFFICE_BEGIN,
  DELETE_OFFICE_SUCCESS,
  DELETE_OFFICE_FAILURE
};
