export const FETCH_USER_COUNT_BY_OFFICE_BEGIN = 'FETCH_USER_COUNT_BY_OFFICE_BEGIN;';
export const FETCH_USER_COUNT_BY_OFFICE_SUCCESS = 'FETCH_USER_COUNT_BY_OFFICE_SUCCESS;';
export const FETCH_USER_COUNT_BY_OFFICE_FAILURE = 'FETCH_USER_COUNT_BY_OFFICE_FAILURE;';

export const FETCH_AWARD_COUNT_BY_USER_BEGIN = 'FETCH_AWARD_COUNT_BY_USER_BEGIN;';
export const FETCH_AWARD_COUNT_BY_USER_SUCCESS = 'FETCH_AWARD_COUNT_BY_USER_SUCCESS;';
export const FETCH_AWARD_COUNT_BY_USER_FAILURE = 'FETCH_AWARD_COUNT_BY_USER_FAILURE;';

export default {
  FETCH_USER_COUNT_BY_OFFICE_BEGIN,
  FETCH_USER_COUNT_BY_OFFICE_SUCCESS,
  FETCH_USER_COUNT_BY_OFFICE_FAILURE,

  FETCH_AWARD_COUNT_BY_USER_BEGIN,
  FETCH_AWARD_COUNT_BY_USER_SUCCESS,
  FETCH_AWARD_COUNT_BY_USER_FAILURE
};
