export const ADMIN_VIEW_USERS = 'ADMIN_VIEW_USERS';
export const ADMIN_VIEW_OFFICES = 'ADMIN_VIEW_OFFICES';
export const SET_THEME_LIGHT = 'SET_THEME_LIGHT';
export const SET_THEME_DARK = 'SET_THEME_DARK';

export default {
  ADMIN_VIEW_USERS,
  ADMIN_VIEW_OFFICES,

  SET_THEME_LIGHT,
  SET_THEME_DARK
};
